CREATE TABLE KMRodado
(
	ID_TABLE INT PRIMARY KEY IDENTITY (1,1),
	DATA_KM DATE,
    SK_VEICULO VARCHAR(50) NOT NULL,
    SK_Motorista VARCHAR(50) NOT NULL,
    KM_PERCORRIDO FLOAT,
    LITROS FLOAT,
    COMBUSTIVEL FLOAT,
    MANUTENCAO FLOAT,
    CUSTO_FIXO FLOAT
)