SELECT
	-- TABELA DE KM RODADO
	KR.DATA_KM,KR.KM_PERCORRIDO,KR.LITROS,KR.COMBUSTIVEL,KR.MANUTENCAO,KR.CUSTO_FIXO,
	-- TABELA DE CADASTRO DOS MOTORISTAS
	CM.Motorista,
	-- TABELA DE CADASTRO DE VEÍCULOS
	CV.Placa, CV.Marca, CV.Tipo_Veiculo, CV.Bau, CV.Ano
FROM KMRodado KR
INNER JOIN CadMotoristas CM ON
	CM.SK_Motorista = KR.SK_Motorista
INNER JOIN CadVeiculos CV ON
	CV.SK_VEICULO = KR.SK_VEICULO