CREATE TABLE CadClientes
(
	ID_TABLE INT PRIMARY KEY IDENTITY (1,1),
	SK_CLIENTE VARCHAR(50) NOT NULL,
	Cidade VARCHAR(150),
    UF VARCHAR(2),
    Cod_Regiao VARCHAR(4) NOT NULL,
    Cod_IBGE VARCHAR(30)
)